all:
	echo "Specify the task number"

1:
	gcc task1.c -o MAIN && ./MAIN

2:
	gcc task2.c -o MAIN && ./MAIN

3:
	gcc task3.c -o MAIN && ./MAIN

4:
	gcc task4.c -o MAIN && ./MAIN
clean:
	rm MAIN && rm a.out